django:
  # Set to false in production!
  debug: true
  # Change in production and keep secret!
  secret_key: 'django-insecure-yp&hf!xk!pybqiek@*r9cq*&0o1p$%80-_6_e!5w)f)_hdrigk'
  # HOST-Header of requests must match one of these
  allowed_hosts:
    - 'localhost'
    - '127.0.0.1'
databases:
  default:
    ENGINE: 'django.db.backends.sqlite3'
    NAME: "BASE_DIR / 'db.sqlite3'"
oauth:
  url_whitelists:
    - 'http://localhost'
    - 'http://127.0.0.1'
  client_name: 'example'
  client_config:
    client_id: ''
    client_secret: '',
    access_token_url: 'https://example.com/login/oauth/access_token'
    authorize_url: 'https://example.com/login/oauth/authorize'
    api_base_url: 'https://api.example.com/'
    redirect_uri: 'https://example.org/oauth/callback'
    client_kwargs:
      scope: 'profile email'
      token_placement: 'header'
    userinfo_endpoint: 'user'
