django:
  # Set to false in production!
  debug: true
  # Change in production and keep secret!
  secret_key: 'changeme'
  # HOST-Header of requests must match one of these
  allowed_hosts:
    - 'localhost'
    - '127.0.0.1'
databases:
  default:
    ENGINE: 'django.db.backends.sqlite3'
    NAME: 'db.sqlite3'
oauth:
  url_whitelists: ['/polls/results']
  client_name: 'zapf-auth'
  client_config:
    client_id: 'changeme'
    client_secret: 'changeme'
    access_token_url: 'https://auth.zapf.in/oauth/token'
    authorize_url: 'https://auth.zapf.in/oauth/authorize'
    api_base_url: 'https://auth.zapf.in/api'
    redirect_uri: 'http://127.0.0.1:8000/oauth/callback'
    client_kwargs:
      scope: 'ownUserData registration uni_list'
      token_placement: 'header'
    userinfo_endpoint: 'api/me'
