# Generated by Django 3.2 on 2021-05-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('polls', '0001_initial'), ('polls', '0002_remove_question_pub_date'), ('polls', '0003_question_active'), ('polls', '0004_auto_20210510_1207'), ('polls', '0005_auto_20210510_1305'), ('polls', '0006_alter_vote_uni')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question')),
            ],
        ),
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('uni_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('uni_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.uni')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.choice')),
            ],
        ),
    ]
